version: "3.7"
services:
  clientnode:
    image: divyeshradadiya/helpinghand-forntend:latest
    ports:
      - "3000:3000"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.5

  servernode:
    image: divyeshradadiya/helpinghand-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    ports:
      - "8081:8081"
    depends_on:
      - "dbnode"
    environment:
      MYSQL_HOST: "dbnode"
      MYSQL_USER: "dvs"
      MYSQL_PASSWORD: "root"
      MYSQL_PORT: "3306"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.6
  dbnode:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - /home/divyesh/dbnode:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "HelpingHand"
      MYSQL_ROOT_USER: "dvs"
      MYSQL_PASSWORD: "root"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.7

networks:
  net_ubuntu:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24



