version: '3'
services:
  react-app:
    image: divyeshradadiya/helpinghand-forntend:latest
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - dvs-app

  hhsqldb:
    container_name: hhsqldb
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dvs
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=HelpingHand
    networks:
      - dvs-app

  springboot-server:
    depends_on:
      - mysql
    image: divyeshradadiya/helpinghand-backend:latest
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: hhsqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

    networks:
      - dvs-app

networks:
  dvs-app:
