---
- name: Pull and Run docker image of divyeshradadiya/helpinghand-forntend
  hosts: all
  tasks:
    - name: remove docker images
      docker_image:
        name: divyeshradadiya/helpinghand-forntend
        state: absent

    - name: remove stopped container
      docker_container:
        name: helpinghand-forntend
        state: absent

    - name: Pull divyeshradadiya/helpinghand-forntend image
      docker_image:
        name: divyeshradadiya/helpinghand-forntend
        source: pull

    - name: create web container
      shell: docker run -d -p 3000:3000 --name helpinghand-forntend divyeshradadiya/helpinghand-forntend
